app:
  http:
    server:
      host: localhost
      port: 8000

  postgres:
    host: localhost
    port: 5432
    database: hezzl_service

  redis:
    host: localhost
    port: 6379
    database: 0


  clickhouse:
    host: localhost
    port: 9000
    database: hezzl_service

  nats:
    publisher:
      host: localhost
      port: 4222
    subscriber:
      host: localhost
      port: 4222