version: "3.8"

services:
  # Service with application container
  hezzl-backend:
    image: hezzl/web-backend
    depends_on:
      postgres-database:
        condition: service_healthy
      redis-database:
        condition: service_started
      clickhouse-database:
        condition: service_healthy
      nats:
        condition: service_started
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - "8000:8000"

  # Service with postgres database container
  postgres-database:
    image: postgres:latest
    volumes:
      - postgres-database:/data/db/postgres
    environment:
      - POSTGRES_DB=hezzl_service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  # Service for managing postgres migrations
  postgres-migrations:
    image: migrate/migrate
    depends_on:
      postgres-database:
        condition: service_healthy
    volumes:
      - ../../migrations/postgres:/data/db/postgres/migrations/postgres
    command:
      [ "-path", "/data/db/postgres/migrations/postgres", "-database", "postgres://postgres:admin@postgres-database:5432/hezzl_service?sslmode=disable", "up" ]

  # Service with redis database container
  redis-database:
    image: redis:latest
    volumes:
      - redis-database:/data/db/redis
    ports:
      - "6379:6379"

  # Service with clickhouse database container
  clickhouse-database:
    image: yandex/clickhouse-server
    volumes:
      - ./users.xml:/etc/clickhouse-server/users.d/users.xml
      - clickhouse-database:/data/db/clickhouse
    environment:
      - CLICKHOUSE_DB=hezzl_service
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=
    ports:
      - "8123:8123"
      - "9000:9000"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8123/?query=SELECT%201 || exit 1

  # Service for managing clickhouse migrations
  clickhouse-migrations:
    image: migrate/migrate
    depends_on:
      clickhouse-database:
        condition: service_healthy
    volumes:
      - ../../migrations/clickhouse:/data/db/clickhouse/migrations/clickhouse
    command:
      [ "-path", "/data/db/clickhouse/migrations/clickhouse", "-database", "clickhouse://clickhouse-database:9000?username=default&password=&database=hezzl_service&x-multi-statement=true", "up" ]

  nats:
    image: nats
    ports:
      - "4222:4222"
      - "8222:8222"

volumes:
  postgres-database:
  redis-database:
  clickhouse-database:
